apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: url:https://github.com/rhdh-qe-2
    backstage.io/managed-by-origin-location: url:https://github.com/rhdh-qe-2
    backstage.io/view-url: https://github.com/rhdh-qe-2
    backstage.io/edit-url: https://github.com/rhdh-qe-2
    backstage.io/source-location: url:https://github.com/
    github.com/user-login: rhdh-qe-2
  name: rhdh-qe-2
  uid: 0be50a7d-9dc1-439e-aa9a-20b050f3c898
  etag: 84bea2e3b2870409fa4f9c6ff222fbaffa1aa4bc
relations:
  - type: memberOf
    targetRef: group:default/rhdh-qe-2-team
spec:
  profile:
    picture: https://avatars.githubusercontent.com/u/177000764?v=4
  memberOf:
    - rhdh-qe-2-team

